# Project Euler Problems #120 to #130

A bag contains one red disc and one blue disc. In a game of chance a player takes a disc at random and its colour is noted. After each turn the disc is returned to the bag, an extra red disc is added, and another disc is taken at random.


The player pays £1 to play and wins if they have taken more blue discs than red discs at the end of the game.


If the game is played for four turns, the probability of a player winning is exactly 11/120, and so the maximum prize fund the banker should allocate for winning in this game would be £10 before they would expect to incur a loss. Note that any payout will be a whole number of pounds and also includes the original £1 paid to play the game, so in the example given the player actually wins £9.


Find the maximum prize fund that should be allocated to a single game in which fifteen turns are played.

The most naive way of computing *n*15 requires fourteen multiplications:


*n* × *n* × ... × *n* = *n*15


But using a "binary" method you can compute it in six multiplications:


*n* × *n* = *n*2  
*n*2 × *n*2 = *n*4  
*n*4 × *n*4 = *n*8  
*n*8 × *n*4 = *n*12  
*n*12 × *n*2 = *n*14  
*n*14 × *n* = *n*15


However it is yet possible to compute it in only five multiplications:


*n* × *n* = *n*2  
*n*2 × *n* = *n*3  
*n*3 × *n*3 = *n*6  
*n*6 × *n*6 = *n*12  
*n*12 × *n*3 = *n*15


We shall define m(*k*) to be the minimum number of multiplications to compute *n**k*; for example m(15) = 5.


For 1 ≤ *k* ≤ 200, find ∑ m(*k*).


Let *p*n be the *n*th prime: 2, 3, 5, 7, 11, ..., and let *r* be the remainder when (*p*n−1)*n* + (*p*n+1)*n* is divided by *p*n2.


For example, when *n* = 3, *p*3 = 5, and 43 + 63 = 280 ≡ 5 mod 25.


The least value of *n* for which the remainder first exceeds 109 is 7037.


Find the least value of *n* for which the remainder first exceeds 1010.

The radical of *n*, rad(*n*), is the product of the distinct prime factors of *n*. For example, 504 = 23 × 32 × 7, so rad(504) = 2 × 3 × 7 = 42.


If we calculate rad(*n*) for *1* ≤ *n* ≤ 10, then sort them on rad(*n*), and sorting on *n* if the radical values are equal, we get:




|  |  |  |
| --- | --- | --- |
| Unsorted |  | Sorted |
| *n* | rad(*n*) |  | *n* | rad(*n*) | k |
| 1 | 1 |  | 1 | 1 | 1 |
| 2 | 2 |  | 2 | 2 | 2 |
| 3 | 3 |  | 4 | 2 | 3 |
| 4 | 2 |  | 8 | 2 | 4 |
| 5 | 5 |  | 3 | 3 | 5 |
| 6 | 6 |  | 9 | 3 | 6 |
| 7 | 7 |  | 5 | 5 | 7 |
| 8 | 2 |  | 6 | 6 | 8 |
| 9 | 3 |  | 7 | 7 | 9 |
| 10 | 10 |  | 10 | 10 | 10 |

Let E(*k*) be the *k*th element in the sorted *n* column; for example, E(4) = 8 and E(6) = 9.


If rad(*n*) is sorted for 1 ≤ *n* ≤ 100000, find E(10000).


The palindromic number 595 is interesting because it can be written as the sum of consecutive squares: 62 + 72 + 82 + 92 + 102 + 112 + 122.


There are exactly eleven palindromes below one-thousand that can be written as consecutive square sums, and the sum of these palindromes is 4164. Note that 1 = 02 + 12 has not been included as this problem is concerned with the squares of positive integers.


Find the sum of all the numbers less than 108 that are both palindromic and can be written as the sum of consecutive squares.

The minimum number of cubes to cover every visible face on a cuboid measuring 3 x 2 x 1 is twenty-two.



![](project/images/p126.png)  

If we then add a second layer to this solid it would require forty-six cubes to cover every visible face, the third layer would require seventy-eight cubes, and the fourth layer would require one-hundred and eighteen cubes to cover every visible face.


However, the first layer on a cuboid measuring 5 x 1 x 1 also requires twenty-two cubes; similarly the first layer on cuboids measuring 5 x 3 x 1, 7 x 2 x 1, and 11 x 1 x 1 all contain forty-six cubes.


We shall define C(*n*) to represent the number of cuboids that contain *n* cubes in one of its layers. So C(22) = 2, C(46) = 4, C(78) = 5, and C(118) = 8.


It turns out that 154 is the least value of *n* for which C(*n*) = 10.


Find the least value of *n* for which C(*n*) = 1000.

The radical of *n*, rad(*n*), is the product of distinct prime factors of *n*. For example, 504 = 23 × 32 × 7, so rad(504) = 2 × 3 × 7 = 42.


We shall define the triplet of positive integers (*a*, *b*, *c*) to be an abc-hit if:


1. GCD(*a,* *b*) = GCD(*a*, *c*) = GCD(*b*, *c*) = 1
2. *a* < *b*
3. *a* + *b* = *c*
4. rad(*abc*) < *c*

For example, (5, 27, 32) is an abc-hit, because:


1. GCD(5, 27) = GCD(5, 32) = GCD(27, 32) = 1
2. 5 < 27
3. 5 + 27 = 32
4. rad(4320) = 30 < 32

It turns out that abc-hits are quite rare and there are only thirty-one abc-hits for *c* < 1000, with ∑*c* = 12523.


Find ∑*c* for *c* < 120000.

A hexagonal tile with number 1 is surrounded by a ring of six hexagonal tiles, starting at "12 o'clock" and numbering the tiles 2 to 7 in an anti-clockwise direction.


New rings are added in the same fashion, with the next rings being numbered 8 to 19, 20 to 37, 38 to 61, and so on. The diagram below shows the first three rings.



![](project/images/p128.png)
By finding the difference between tile *n* and each of its six neighbours we shall define PD(*n*) to be the number of those differences which are prime.


For example, working clockwise around tile 8 the differences are 12, 29, 11, 6, 1, and 13. So PD(8) = 3.


In the same way, the differences around tile 17 are 1, 17, 16, 1, 11, and 10, hence PD(17) = 2.


It can be shown that the maximum value of PD(*n*) is 3.


If all of the tiles for which PD(*n*) = 3 are listed in ascending order to form a sequence, the 10th tile would be 271.


Find the 2000th tile in this sequence.


A number consisting entirely of ones is called a repunit. We shall define R(*k*) to be a repunit of length *k*; for example, R(6) = 111111.


Given that *n* is a positive integer and GCD(*n*, 10) = 1, it can be shown that there always exists a value, *k*, for which R(*k*) is divisible by *n*, and let A(*n*) be the least such value of *k*; for example, A(7) = 6 and A(41) = 5.


The least value of *n* for which A(*n*) first exceeds ten is 17.


Find the least value of *n* for which A(*n*) first exceeds one-million.


A number consisting entirely of ones is called a repunit. We shall define R(*k*) to be a repunit of length *k*; for example, R(6) = 111111.


Given that *n* is a positive integer and GCD(*n*, 10) = 1, it can be shown that there always exists a value, *k*, for which R(*k*) is divisible by *n*, and let A(*n*) be the least such value of *k*; for example, A(7) = 6 and A(41) = 5.


You are given that for all primes, *p* > 5, that *p* − 1 is divisible by A(*p*). For example, when *p* = 41, A(41) = 5, and 40 is divisible by 5.


However, there are rare composite values for which this is also true; the first five examples being 91, 259, 451, 481, and 703.


Find the sum of the first twenty-five composite values of *n* for which  
GCD(*n*, 10) = 1 and *n* − 1 is divisible by A(*n*).