# Project Euler Problems #60 to #70

Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:




|  |  |  |  |  |
| --- | --- | --- | --- | --- |
| Triangle |  | P3,*n*=*n*(*n*+1)/2 |  | 1, 3, 6, 10, 15, ... |
| Square |  | P4,*n*=*n*2 |  | 1, 4, 9, 16, 25, ... |
| Pentagonal |  | P5,*n*=*n*(3*n*−1)/2 |  | 1, 5, 12, 22, 35, ... |
| Hexagonal |  | P6,*n*=*n*(2*n*−1) |  | 1, 6, 15, 28, 45, ... |
| Heptagonal |  | P7,*n*=*n*(5*n*−3)/2 |  | 1, 7, 18, 34, 55, ... |
| Octagonal |  | P8,*n*=*n*(3*n*−2) |  | 1, 8, 21, 40, 65, ... |

The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.


1. The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).
2. Each polygonal type: triangle (P3,127=8128), square (P4,91=8281), and pentagonal (P5,44=2882), is represented by a different number in the set.
3. This is the only set of 4-digit numbers with this property.

Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.

The cube, 41063625 (3453), can be permuted to produce two other cubes: 56623104 (3843) and 66430125 (4053). In fact, 41063625 is the smallest cube which has exactly three permutations of its digits which are also cube.


Find the smallest cube for which exactly five permutations of its digits are cube.


The 5-digit number, 16807=75, is also a fifth power. Similarly, the 9-digit number, 134217728=89, is a ninth power.


How many *n*-digit positive integers exist which are also an *n*th power?

All square roots are periodic when written as continued fractions and can be written in the form:



$\displaystyle \quad \quad \sqrt{N}=a\_0+\frac 1 {a\_1+\frac 1 {a\_2+ \frac 1 {a3+ \dots}}}$

For example, let us consider $\sqrt{23}:$


$\quad \quad \sqrt{23}=4+\sqrt{23}-4=4+\frac 1 {\frac 1 {\sqrt{23}-4}}=4+\frac 1 {1+\frac{\sqrt{23}-3}7}$

If we continue we would get the following expansion:



$\displaystyle \quad \quad \sqrt{23}=4+\frac 1 {1+\frac 1 {3+ \frac 1 {1+\frac 1 {8+ \dots}}}}$

The process can be summarised as follows:



$\quad \quad a\_0=4, \frac 1 {\sqrt{23}-4}=\frac {\sqrt{23}+4} 7=1+\frac {\sqrt{23}-3} 7$  

$\quad \quad a\_1=1, \frac 7 {\sqrt{23}-3}=\frac {7(\sqrt{23}+3)} {14}=3+\frac {\sqrt{23}-3} 2$  

$\quad \quad a\_2=3, \frac 2 {\sqrt{23}-3}=\frac {2(\sqrt{23}+3)} {14}=1+\frac {\sqrt{23}-4} 7$  

$\quad \quad a\_3=1, \frac 7 {\sqrt{23}-4}=\frac {7(\sqrt{23}+4)} 7=8+\sqrt{23}-4$  

$\quad \quad a\_4=8, \frac 1 {\sqrt{23}-4}=\frac {\sqrt{23}+4} 7=1+\frac {\sqrt{23}-3} 7$  

$\quad \quad a\_5=1, \frac 7 {\sqrt{23}-3}=\frac {7 (\sqrt{23}+3)} {14}=3+\frac {\sqrt{23}-3} 2$  


$\quad \quad a\_6=3, \frac 2 {\sqrt{23}-3}=\frac {2(\sqrt{23}+3)} {14}=1+\frac {\sqrt{23}-4} 7$  

$\quad \quad a\_7=1, \frac 7 {\sqrt{23}-4}=\frac {7(\sqrt{23}+4)} {7}=8+\sqrt{23}-4$  



It can be seen that the sequence is repeating. For conciseness, we use the notation $\sqrt{23}=[4;(1,3,1,8)]$, to indicate that the block (1,3,1,8) repeats indefinitely.


The first ten continued fraction representations of (irrational) square roots are:



$\quad \quad \sqrt{2}=[1;(2)]$, period=$1$  

$\quad \quad \sqrt{3}=[1;(1,2)]$, period=$2$  

$\quad \quad \sqrt{5}=[2;(4)]$, period=$1$  

$\quad \quad \sqrt{6}=[2;(2,4)]$, period=$2$  

$\quad \quad \sqrt{7}=[2;(1,1,1,4)]$, period=$4$  

$\quad \quad \sqrt{8}=[2;(1,4)]$, period=$2$  

$\quad \quad \sqrt{10}=[3;(6)]$, period=$1$  

$\quad \quad \sqrt{11}=[3;(3,6)]$, period=$2$  

$\quad \quad \sqrt{12}=[3;(2,6)]$, period=$2$  

$\quad \quad \sqrt{13}=[3;(1,1,1,1,6)]$, period=$5$



Exactly four continued fractions, for $N \le 13$, have an odd period.


How many continued fractions for $N \le 10\,000$ have an odd period?

The square root of 2 can be written as an infinite continued fraction.


$\sqrt{2} = 1 + \dfrac{1}{2 + \dfrac{1}{2 + \dfrac{1}{2 + \dfrac{1}{2 + ...}}}}$


The infinite continued fraction can be written, $\sqrt{2} = [1; (2)]$, $(2)$ indicates that 2 repeats *ad infinitum*. In a similar way, $\sqrt{23} = [4; (1, 3, 1, 8)]$.


It turns out that the sequence of partial values of continued fractions for square roots provide the best rational approximations. Let us consider the convergents for $\sqrt{2}$.


$\begin{align}
&1 + \dfrac{1}{2} = \dfrac{3}{2} \\
&1 + \dfrac{1}{2 + \dfrac{1}{2}} = \dfrac{7}{5}\\
&1 + \dfrac{1}{2 + \dfrac{1}{2 + \dfrac{1}{2}}} = \dfrac{17}{12}\\
&1 + \dfrac{1}{2 + \dfrac{1}{2 + \dfrac{1}{2 + \dfrac{1}{2}}}} = \dfrac{41}{29}
\end{align}$


Hence the sequence of the first ten convergents for $\sqrt{2}$ are:


$1, \dfrac{3}{2}, \dfrac{7}{5}, \dfrac{17}{12}, \dfrac{41}{29}, \dfrac{99}{70}, \dfrac{239}{169}, \dfrac{577}{408}, \dfrac{1393}{985}, \dfrac{3363}{2378}, ...$


What is most surprising is that the important mathematical constant,  
$e = [2; 1, 2, 1, 1, 4, 1, 1, 6, 1, ... , 1, 2k, 1, ...]$.


The first ten terms in the sequence of convergents for *e* are:


$2, 3, \dfrac{8}{3}, \dfrac{11}{4}, \dfrac{19}{7}, \dfrac{87}{32}, \dfrac{106}{39}, \dfrac{193}{71}, \dfrac{1264}{465}, \dfrac{1457}{536}, ...$


The sum of digits in the numerator of the 10th convergent is $1 + 4 + 5 + 7 = 17$.


Find the sum of digits in the numerator of the 100th convergent of the continued fraction for $e$.

Consider quadratic Diophantine equations of the form:


*x*2 – D*y*2 = 1


For example, when D=13, the minimal solution in *x* is 6492 – 13×1802 = 1.


It can be assumed that there are no solutions in positive integers when D is square.


By finding minimal solutions in *x* for D = {2, 3, 5, 6, 7}, we obtain the following:


32 – 2×22 = 1  

22 – 3×12 = 1  
92 – 5×42 = 1  

52 – 6×22 = 1  

82 – 7×32 = 1


Hence, by considering minimal solutions in *x* for D ≤ 7, the largest *x* is obtained when D=5.


Find the value of D ≤ 1000 in minimal solutions of *x* for which the largest value of *x* is obtained.

By starting at the top of the triangle below and moving to adjacent numbers on the row below, the maximum total from top to bottom is 23.


**3**  
**7** 4  

2 **4** 6  

8 5 **9** 3


That is, 3 + 7 + 4 + 9 = 23.


Find the maximum total from top to bottom in [triangle.txt](project/resources/p067_triangle.txt) (right click and 'Save Link/Target As...'), a 15K text file containing a triangle with one-hundred rows.


**NOTE:** This is a much more difficult version of [Problem 18](problem=18). It is not possible to try every route to solve this problem, as there are 299 altogether! If you could check one trillion (1012) routes every second it would take over twenty billion years to check them all. There is an efficient algorithm to solve it. ;o)

Consider the following "magic" 3-gon ring, filled with the numbers 1 to 6, and each line adding to nine.



![](project/images/p068_1.png)  

Working **clockwise**, and starting from the group of three with the numerically lowest external node (4,3,2 in this example), each solution can be described uniquely. For example, the above solution can be described by the set: 4,3,2; 6,2,1; 5,1,3.


It is possible to complete the ring with four different totals: 9, 10, 11, and 12. There are eight solutions in total.





|  |  |
| --- | --- |
| **Total** | **Solution Set** |
| 9 | 4,2,3; 5,3,1; 6,1,2 |
| 9 | 4,3,2; 6,2,1; 5,1,3 |
| 10 | 2,3,5; 4,5,1; 6,1,3 |
| 10 | 2,5,3; 6,3,1; 4,1,5 |
| 11 | 1,4,6; 3,6,2; 5,2,4 |
| 11 | 1,6,4; 5,4,2; 3,2,6 |
| 12 | 1,5,6; 2,6,4; 3,4,5 |
| 12 | 1,6,5; 3,5,4; 2,4,6 |


By concatenating each group it is possible to form 9-digit strings; the maximum string for a 3-gon ring is 432621513.


Using the numbers 1 to 10, and depending on arrangements, it is possible to form 16- and 17-digit strings. What is the maximum **16-digit** string for a "magic" 5-gon ring?



![](project/images/p068_2.png)

Euler's Totient function, φ(*n*) [sometimes called the phi function], is used to determine the number of numbers less than *n* which are relatively prime to *n*. For example, as 1, 2, 4, 5, 7, and 8, are all less than nine and relatively prime to nine, φ(9)=6.





|  |  |  |  |
| --- | --- | --- | --- |
| ***n*** | **Relatively Prime** | **φ(*n*)** | ***n*/φ(*n*)** |
| 2 | 1 | 1 | 2 |
| 3 | 1,2 | 2 | 1.5 |
| 4 | 1,3 | 2 | 2 |
| 5 | 1,2,3,4 | 4 | 1.25 |
| 6 | 1,5 | 2 | 3 |
| 7 | 1,2,3,4,5,6 | 6 | 1.1666... |
| 8 | 1,3,5,7 | 4 | 2 |
| 9 | 1,2,4,5,7,8 | 6 | 1.5 |
| 10 | 1,3,7,9 | 4 | 2.5 |


It can be seen that *n*=6 produces a maximum *n*/φ(*n*) for *n* ≤ 10.


Find the value of *n* ≤ 1,000,000 for which *n*/φ(*n*) is a maximum.

Euler's Totient function, φ(n) [sometimes called the phi function], is used to determine the number of positive numbers less than or equal to n which are relatively prime to n. For example, as 1, 2, 4, 5, 7, and 8, are all less than nine and relatively prime to nine, φ(9)=6.  
The number 1 is considered to be relatively prime to every positive number, so φ(1)=1. 


Interestingly, φ(87109)=79180, and it can be seen that 87109 is a permutation of 79180.


Find the value of n, 1 < n < 107, for which φ(n) is a permutation of n and the ratio n/φ(n) produces a minimum.